SET SERVEROUTPUT ON;

CREATE OR REPLACE PACKAGE REPORT2 AS

/*


-- Which registered customers have shopped with us before?
SELECT DISTINCT CUSTOMERS.CUSTOMER_ID, CUSTOMERS.FIRST_NAME, CUSTOMERS.SURNAME, CUSTOMERS.EMAIL
FROM CUSTOMERS
INNER JOIN ORDERS ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID;

ANSWER: NOT ALL REGISTERED CUST HAVE BOUGHT. SOME ONLY HAVE ACCOUNTS AND NO PURCHASE



-- How much has each customer spent over time?
SELECT
    CUSTOMERS.CUSTOMER_ID,
    CUSTOMERS.FIRST_NAME,
    CUSTOMERS.SURNAME,
    CUSTOMERS.EMAIL,
    SUM(ORDERS.TOTAL) AS TOTAL_SPENT
FROM CUSTOMERS
INNER JOIN ORDERS ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID
GROUP BY CUSTOMERS.CUSTOMER_ID, CUSTOMERS.FIRST_NAME, CUSTOMERS.SURNAME, CUSTOMERS.EMAIL;

ANSWER: THE AVG TOTAL DIFFERS QUITE A LOT FROM 70 TO OVER 200.



--What's the age of these customers? Is there a correlation between older = spends more?
SELECT CUSTOMERS.CUSTOMER_ID, CUSTOMERS.FIRST_NAME, CUSTOMERS.SURNAME, CUSTOMERS.EMAIL, CUSTOMERS.BIRTHDATE,
    SUM(ORDERS.TOTAL) AS TOTAL_SPENT
FROM CUSTOMERS
INNER JOIN ORDERS ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID
GROUP BY CUSTOMERS.CUSTOMER_ID, CUSTOMERS.FIRST_NAME, CUSTOMERS.SURNAME, CUSTOMERS.EMAIL, CUSTOMERS.BIRTHDATE;

ANSWER: THE OLDER THE CUSTOMER, THE MORE LIKELY THEY ARE TO SPEND MORE.



--What products are these customers buying? Is there a popular item?
SELECT C.CUSTOMER_ID, C.FIRST_NAME, C.SURNAME, P.PRODUCT_ID, P.NAME
FROM CUSTOMERS C
INNER JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
INNER JOIN PRODUCTS P ON O.PRODUCT_ID = P.PRODUCT_ID;

ANSWER: ALL CUSTOMERS HAVE BOUGHT MATCHA, SOME HAVE TRIED OTHER PRODUCTS TOO



--How many times have they bought the same item? Are they returning for the same item?
SELECT C.CUSTOMER_ID, C.FIRST_NAME, C.SURNAME, P.PRODUCT_ID, P.NAME,
    COUNT(*) AS popularity
FROM CUSTOMERS C
INNER JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
INNER JOIN PRODUCTS P ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    C.CUSTOMER_ID,
    C.FIRST_NAME,
    C.SURNAME,
    P.PRODUCT_ID,
    P.NAME
ORDER BY popularity DESC;

ANSWER: CUSTOMERS DO NOT REPURCHASE THE SAME ITEM AGAIN, THEY TRY OUT NEW PRODUCTS INSTEAD.



*/



END REPORT2;